version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    shm_size: '256mb'
    volumes:
      - .:/myapp
      - bundle:/myapp/vendor/bundle
    env_file:
      - .env
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - 3001:3000

  netkeiba_mock:
    build:
      context: ./netkeiba_mock
    image: netkeiba_mock
    volumes:
      - ./netkeiba_mock/nginx_root:/data/nginx_root
    ports:
      - 8080:80

  chrome:
    image: selenium/standalone-chrome
    shm_size: '256mb'
    ports:
      - '4444:4444'

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 54322:5432
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  bundle:
  db-data: